<?
$arUrlRewriteExtra = [
    array(
        'CONDITION' => '#^' . C_SITE_DIR . '\\.well-known#',
        'RULE' => '',
        'ID' => '',
        'PATH' => '/bitrix/groupdav.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'about/gallery/#',
        'RULE' => '',
        'ID' => 'bitrix:photogallery',
        'PATH' => C_SITE_DIR . 'about/gallery/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'bitrix/services/ymarket/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => '/bitrix/services/ymarket/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'bizproc/list/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => '/bizproc/list/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'bizproc/list/bp_mp/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => '/bizproc/list/bp_mp/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'bizproc/processes/#',
        'RULE' => '',
        'ID' => 'bitrix:lists',
        'PATH' => C_SITE_DIR . 'bizproc/processes/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'company/gallery/#',
        'RULE' => '',
        'ID' => 'bitrix:photogallery_user',
        'PATH' => C_SITE_DIR . 'company/gallery/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'company/personal/#',
        'RULE' => '',
        'ID' => 'bitrix:socialnetwork_user',
        'PATH' => C_SITE_DIR . 'company/personal.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/activity/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.activity',
        'PATH' => C_SITE_DIR . 'crm/activity/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/button/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.button',
        'PATH' => C_SITE_DIR . 'crm/button/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/company/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.company',
        'PATH' => C_SITE_DIR . 'crm/company/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/configs/automation/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.config.automation',
        'PATH' => C_SITE_DIR . 'crm/configs/automation/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/configs/bp/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.config.bp',
        'PATH' => C_SITE_DIR . 'crm/configs/bp/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/configs/currency/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.currency',
        'PATH' => C_SITE_DIR . 'crm/configs/currency/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/configs/deal_category/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.deal_category',
        'PATH' => C_SITE_DIR . 'crm/configs/deal_category/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/configs/document_numerators/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.document_numerators.list',
        'PATH' => C_SITE_DIR . 'crm/configs/document_numerators/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/configs/exch1c/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.config.exch1c',
        'PATH' => C_SITE_DIR . 'crm/configs/exch1c/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/configs/exclusion/#',
        'RULE' => '',
        'ID' => NULL,
        'PATH' => C_SITE_DIR . 'crm/configs/exclusion/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/configs/fields/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.config.fields',
        'PATH' => C_SITE_DIR . 'crm/configs/fields/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/configs/locations/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.config.locations',
        'PATH' => C_SITE_DIR . 'crm/configs/locations/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/configs/mailtemplate/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.mail_template',
        'PATH' => C_SITE_DIR . 'crm/configs/mailtemplate/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/configs/measure/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.config.measure',
        'PATH' => C_SITE_DIR . 'crm/configs/measure/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/configs/mycompany/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.company',
        'PATH' => C_SITE_DIR . 'crm/configs/mycompany/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/configs/perms/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.config.perms',
        'PATH' => C_SITE_DIR . 'crm/configs/perms/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/configs/preset/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.config.preset',
        'PATH' => C_SITE_DIR . 'crm/configs/preset/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/configs/productprops/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.config.productprops',
        'PATH' => C_SITE_DIR . 'crm/configs/productprops/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/configs/ps/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.config.ps',
        'PATH' => C_SITE_DIR . 'crm/configs/ps/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/configs/tax/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.config.tax',
        'PATH' => C_SITE_DIR . 'crm/configs/tax/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/configs/volume/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.volume',
        'PATH' => C_SITE_DIR . 'crm/configs/volume/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/contact/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.contact',
        'PATH' => C_SITE_DIR . 'crm/contact/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/deal/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.deal',
        'PATH' => C_SITE_DIR . 'crm/deal/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/invoice/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.invoice',
        'PATH' => C_SITE_DIR . 'crm/invoice/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/invoicing/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => C_SITE_DIR . 'crm/invoicing/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/lead/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.lead',
        'PATH' => C_SITE_DIR . 'crm/lead/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/product/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.product',
        'PATH' => C_SITE_DIR . 'crm/product/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/quote/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.quote',
        'PATH' => C_SITE_DIR . 'crm/quote/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/reports/report/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.report',
        'PATH' => C_SITE_DIR . 'crm/reports/report/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/webform/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.webform',
        'PATH' => C_SITE_DIR . 'crm/webform/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'disk/(?<action>[0-9a-zA-Z]+)/(?<fileId>[0-9]+)/\\?#',
        'RULE' => 'action=$1&fileId=$2&',
        'ID' => 'bitrix:disk.services',
        'PATH' => '/bitrix/services/disk/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'docs/all#',
        'RULE' => '',
        'ID' => 'bitrix:disk.aggregator',
        'PATH' => C_SITE_DIR . 'docs/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'docs/manage/#',
        'RULE' => '',
        'ID' => 'bitrix:disk.common',
        'PATH' => C_SITE_DIR . 'docs/manage/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'docs/pub/(?<hash>[0-9a-f]{32})/(?<action>[0-9a-zA-Z]+)/\\?#',
        'RULE' => 'hash=$1&action=$2&',
        'ID' => 'bitrix:disk.external.link',
        'PATH' => '/docs/pub/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'docs/pub/#',
        'RULE' => '',
        'ID' => 'bitrix:disk.external.link',
        'PATH' => '/docs/pub/extlinks.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'docs/sale/#',
        'RULE' => '',
        'ID' => 'bitrix:disk.common',
        'PATH' => C_SITE_DIR . 'docs/sale/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'docs/shared#',
        'RULE' => '',
        'ID' => 'bitrix:disk.common',
        'PATH' => C_SITE_DIR . 'docs/shared/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'mail/#',
        'RULE' => '',
        'ID' => 'bitrix:mail.client',
        'PATH' => C_SITE_DIR . 'mail/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'marketing/ads/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => C_SITE_DIR . 'marketing/ads.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'marketing/blacklist/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => C_SITE_DIR . 'marketing/blacklist.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'marketing/config/role/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => C_SITE_DIR . 'marketing/config/role.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'marketing/contact/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => C_SITE_DIR . 'marketing/contact.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'marketing/letter/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => C_SITE_DIR . 'marketing/letter.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'marketing/rc/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => C_SITE_DIR . 'marketing/rc.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'marketing/segment/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => C_SITE_DIR . 'marketing/segment.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'marketing/template/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => C_SITE_DIR . 'marketing/template.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'marketplace/#',
        'RULE' => '',
        'ID' => 'bitrix:rest.marketplace',
        'PATH' => '/marketplace/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'marketplace/app/#',
        'RULE' => '',
        'ID' => 'bitrix:app.layout',
        'PATH' => '/marketplace/app/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'marketplace/hook/#',
        'RULE' => '',
        'ID' => 'bitrix:rest.hook',
        'PATH' => '/marketplace/hook/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'marketplace/local/#',
        'RULE' => '',
        'ID' => 'bitrix:rest.marketplace.localapp',
        'PATH' => '/marketplace/local/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'mobile/disk/(?<hash>[0-9]+)/download#',
        'RULE' => 'download=1&objectId=$1',
        'ID' => 'bitrix:mobile.disk.file.detail',
        'PATH' => '/mobile/disk/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'mobile/webdav#',
        'RULE' => '',
        'ID' => 'bitrix:mobile.webdav.file.list',
        'PATH' => '/mobile/webdav/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'onec/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.1C.start',
        'PATH' => C_SITE_DIR . 'onec/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'online/(/?)([^/]*)#',
        'RULE' => '',
        'ID' => '',
        'PATH' => '/desktop_app/router.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'online/([\\.\\-0-9a-zA-Z]+)(/?)([^/]*)#',
        'RULE' => 'alias=$1',
        'ID' => '',
        'PATH' => '/desktop_app/router.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'pub/document/([0-9a-zA-Z_-]+)/([0-9a-zA-Z]+)/([^/]*)#',
        'RULE' => 'id=$1&hash=$2',
        'ID' => 'bitrix:documentgenerator.view',
        'PATH' => C_SITE_DIR . 'pub/document.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'pub/form/([0-9a-z_]+?)/([0-9a-z]+?)/.*#',
        'RULE' => 'form_code=$1&sec=$2',
        'ID' => 'bitrix:crm.webform.fill',
        'PATH' => C_SITE_DIR . 'pub/form.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'pub/pay/([\\w\\W]+)/([0-9a-zA-Z]+)/([^/]*)#',
        'RULE' => 'account_number=$1&hash=$2',
        'ID' => '',
        'PATH' => C_SITE_DIR . 'pub/payment.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'pub/site/(.*?)#',
        'RULE' => 'path=$1',
        'ID' => 'bitrix:landing.pub',
        'PATH' => C_SITE_DIR . 'pub/site/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'rest/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => '/bitrix/services/rest/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'services/faq/#',
        'RULE' => '',
        'ID' => 'bitrix:support.faq',
        'PATH' => C_SITE_DIR . 'services/faq/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'services/idea/#',
        'RULE' => '',
        'ID' => 'bitrix:idea',
        'PATH' => C_SITE_DIR . 'services/idea/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'services/lists/#',
        'RULE' => '',
        'ID' => 'bitrix:lists',
        'PATH' => C_SITE_DIR . 'services/lists/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'services/processes/#',
        'RULE' => '',
        'ID' => 'bitrix:lists',
        'PATH' => C_SITE_DIR . 'services/processes/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'services/wiki/#',
        'RULE' => '',
        'ID' => 'bitrix:wiki',
        'PATH' => C_SITE_DIR . 'services/wiki.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'settings/configs/userconsent/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => C_SITE_DIR . 'configs/userconsent.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'shop/buyer/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.order.buyer',
        'PATH' => C_SITE_DIR . 'shop/buyer/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'shop/buyer_group/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.order.buyer_group',
        'PATH' => C_SITE_DIR . 'shop/buyer_group/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'shop/orderform/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.order.matcher',
        'PATH' => C_SITE_DIR . 'shop/orderform/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'shop/orders/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.order',
        'PATH' => C_SITE_DIR . 'shop/orders/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'shop/settings/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.admin.page.controller',
        'PATH' => C_SITE_DIR . 'shop/settings/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'shop/stores/#',
        'RULE' => '',
        'ID' => 'bitrix:landing.start',
        'PATH' => C_SITE_DIR . 'shop/stores/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'sites/#',
        'RULE' => NULL,
        'ID' => 'bitrix:landing.start',
        'PATH' => '/sites/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'stssync/calendar/#',
        'RULE' => '',
        'ID' => 'bitrix:stssync.server',
        'PATH' => '/bitrix/services/stssync/calendar/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'stssync/contacts/#',
        'RULE' => '',
        'ID' => 'bitrix:stssync.server',
        'PATH' => '/bitrix/services/stssync/contacts/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'stssync/contacts_crm/#',
        'RULE' => '',
        'ID' => 'bitrix:stssync.server',
        'PATH' => '/bitrix/services/stssync/contacts_crm/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'stssync/tasks/#',
        'RULE' => '',
        'ID' => 'bitrix:stssync.server',
        'PATH' => '/bitrix/services/stssync/tasks/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'tasks/getfile/(\\d+)/(\\d+)/([^/]+)#',
        'RULE' => 'taskid=$1&fileid=$2&filename=$3',
        'ID' => 'bitrix:tasks_tools_getfile',
        'PATH' => C_SITE_DIR . 'tasks/getfile.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'timeman/meeting/#',
        'RULE' => '',
        'ID' => 'bitrix:meetings',
        'PATH' => C_SITE_DIR . 'timeman/meeting/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'workgroups/#',
        'RULE' => '',
        'ID' => 'bitrix:socialnetwork_group',
        'PATH' => C_SITE_DIR . 'workgroups/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^/online/call/([\\.\\-0-9a-zA-Z]+)(/?)([^/]*)#',
        'RULE' => 'alias=$1',
        'ID' => NULL,
        'PATH' => '/desktop_app/router.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^\\/?\\/mobile/mobile_component\\/(.*)\\/.*#',
        'RULE' => 'componentName=$1',
        'ID' => 'mobile_js_component',
        'PATH' => '/bitrix/services/mobile/jscomponent.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^\\/?\\/mobile/mobile_component\\/(.*)\\/.*#',
        'RULE' => 'componentName=$1',
        'ID' => '',
        'PATH' => '/bitrix/services/mobile/jscomponent.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^\\/?\\/mobile/web_mobile_component\\/(.*)\\/.*#',
        'RULE' => 'componentName=$1',
        'ID' => '',
        'PATH' => '/bitrix/services/mobile/webcomponent.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^\\/?\\/mobileapp/jn\\/(.*)\\/.*#',
        'RULE' => 'componentName=$1',
        'ID' => NULL,
        'PATH' => '/bitrix/services/mobileapp/jn.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'zayavka-na-vremennyy-propusk/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => '/zayavka-na-vremennyy-propusk/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'company/leaders/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => C_SITE_DIR . 'company/leaders.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'raschetnyy-listok/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => '/raschetnyy-listok/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'about/business_news.php#',
        'RULE' => '',
        'ID' => '',
        'PATH' => '/about/business_news.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'planner/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => '/planner/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'it-news/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => '/it-news/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . '10let/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => '/10let/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'votes/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => '/votes/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'company/vis_structure.php#',
        'RULE' => '',
        'ID' => '',
        'PATH' => '/company/vis_structure.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'scud#',
        'RULE' => '',
        'ID' => '',
        'PATH' => '/timeman/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'isolation/api/v([0-9]+)/([a-zA-Z0-9\\.\\-_]+)?.*#',
        'RULE' => 'version=$1&action=$2',
        'ID' => '',
        'PATH' => '/isolation/api/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'rpa/#',
        'RULE' => '',
        'ID' => 'bitrix:rpa.router',
        'PATH' => C_SITE_DIR . 'rpa/index.php',
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'kb/#',
        'RULE' => '',
        'ID' => 'bitrix:landing.start',
        'PATH' => C_SITE_DIR . 'kb/index.php',
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'knowledge/group/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => C_SITE_DIR . 'knowledge/group/index.php',
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'knowledge/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => C_SITE_DIR . 'knowledge/index.php',
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'timeman/schedules/#',
        'RULE' => '',
        'ID' => 'bitrix:timeman.schedules',
        'PATH' => C_SITE_DIR . 'timeman/schedules.php',
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'timeman/settings/#',
        'RULE' => '',
        'ID' => 'bitrix:timeman.schedules',
        'PATH' => C_SITE_DIR . 'timeman/settings.php',
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'timeman/worktime/#',
        'RULE' => '',
        'ID' => 'bitrix:timeman.worktime',
        'PATH' => C_SITE_DIR . 'timeman/worktime.php',
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'video/([\\.\\-0-9a-zA-Z]+)(/?)([^/]*)#',
        'RULE' => 'alias=$1&videoconf',
        'ID' => 'bitrix:im.router',
        'PATH' => '/desktop_app/router.php',
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'marketing/toloka/#',
        'RULE' => '',
        'ID' => 'bitrix:sender.yandex.toloka',
        'PATH' => '/marketing/toloka.php',
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'shop/catalog/#',
        'RULE' => '',
        'ID' => 'bitrix:catalog.productcard.controller',
        'PATH' => C_SITE_DIR . 'shop/catalog/index.php',
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'crm/catalog/#',
        'RULE' => '',
        'ID' => 'bitrix:crm.catalog.controller',
        'PATH' => C_SITE_DIR . 'crm/catalog/index.php',
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'conference/#',
        'RULE' => '',
        'ID' => 'bitrix:im.conference.center',
        'PATH' => C_SITE_DIR . 'conference/index.php',
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'devops/#',
        'RULE' => NULL,
        'ID' => 'bitrix:rest.devops',
        'PATH' => C_SITE_DIR . 'devops/index.php',
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'kpi/([a-zA-Z0-9\\.\\-_]+)?.*#',
        'RULE' => 'page=$1',
        'ID' => '',
        'PATH' => C_SITE_DIR . 'kpi/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'test-kpi/([a-zA-Z0-9\\.\\-_]+)?.*#',
        'RULE' => 'page=$1',
        'ID' => '',
        'PATH' => C_SITE_DIR . 'test-kpi/index.php',
        'SORT' => 100,
    ),
    array(
        'CONDITION' => '#^' . C_SITE_DIR . 'vaccination/([a-zA-Z0-9\\.\\-_]+)?.*#',
        'RULE' => 'page=$1',
        'ID' => '',
        'PATH' => '/vaccination/index.php',
        'SORT' => 100,
    ),
];

$arUrlRewrite = array_merge($arUrlRewrite, $arUrlRewriteExtra);
