<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();
IncludeModuleLangFile($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/intranet/public/.bottom.menu.php");

$aMenuLinks = Array(
	Array(
		GetMessage("BOTTOM_MENU_PRINT_VERSION"),
		"#print", 
		Array(),
		Array(),
		""
	),
	Array(
		GetMessage("BOTTOM_MENU_CONTACTS"),
		"/czn/about/company/contacts.php",
		Array(), 
		Array(), 
		"" 
	),
	Array(
		GetMessage("BOTTOM_MENU_SEARCH"),
		"/czn/search/",
		Array(), 
		Array(), 
		"" 
	),
	Array(
		GetMessage("BOTTOM_MENU_MAP"),
		"/czn/search/map.php",
		Array(), 
		Array(), 
		"" 
	),
	Array(
		GetMessage("BOTTOM_MENU_HELP"),
		"/czn/services/help/",
		Array(), 
		Array(), 
		"" 
	),
);
?>