<?
if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true) die();
IncludeModuleLangFile($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/intranet/public/services/.left.menu.php");

$aMenuLinks = Array(
	Array(
		GetMessage("SERVICES_MENU_MEETING_ROOM"),
		"/edu/services/index.php",
		Array("/edu/services/res_c.php"),
		Array(),
		"CBXFeatures::IsFeatureEnabled('MeetingRoomBookingSystem')"
	),
	Array(
		GetMessage("SERVICES_MENU_IDEA"),
		"/edu/services/idea/",
		Array(),
		Array(),
		"CBXFeatures::IsFeatureEnabled('Idea')"
	),
	Array(
		GetMessage("SERVICES_MENU_LISTS"),
		"/edu/services/lists/",
		Array(),
		Array(),
		"CBXFeatures::IsFeatureEnabled('Lists')"
	),
	Array(
		GetMessage("SERVICES_MENU_REQUESTS"),
		"/edu/services/requests/",
		Array(),
		Array(),
		(!IsModuleInstalled("form"))?"false":"CBXFeatures::IsFeatureEnabled('Requests')"
	),
	Array(
		GetMessage("SERVICES_MENU_LEARNING"),
		"/edu/services/learning/",
		Array("/services/course.php"),
		Array(),
		"CBXFeatures::IsFeatureEnabled('Learning')"
	),
	Array(
		GetMessage("SERVICES_MENU_WIKI"),
		"/edu/services/wiki/",
		Array(),
		Array(),
		"CBXFeatures::IsFeatureEnabled('Wiki')"
	),
	Array(
		GetMessage("SERVICES_MENU_CONTACT_CENTER"),
		"/edu/services/contact_center/",
		Array(),
		Array(),
		""
	),
	Array(
		GetMessage("SERVICES_MENU_FAQ"),
		"/edu/services/faq/",
		Array(),
		Array(),
		""
	),
	Array(
		GetMessage("SERVICES_MENU_VOTE"),
		"/edu/services/votes.php",
		Array("/edu/services/vote_new.php", "/edu/services/vote_result.php"),
		Array(),
		"CBXFeatures::IsFeatureEnabled('Vote')"
	),
	Array(
		GetMessage("SERVICES_MENU_SUPPORT"),
		"/edu/services/support.php?show_wizard=Y",
		Array("/edu/services/support.php"),
		Array(),
		(!IsModuleInstalled("support"))?"false":"CBXFeatures::IsFeatureEnabled('Support')"
	),
	Array(
		GetMessage("SERVICES_MENU_LINKS"),
		"/edu/services/links.php",
		Array(),
		Array(),
		"CBXFeatures::IsFeatureEnabled('WebLink')"
	),
	Array(
		GetMessage("SERVICES_MENU_SUBSCR"),
		"/edu/services/subscr_edit.php",
		Array(),
		Array(),
		"CBXFeatures::IsFeatureEnabled('Subscribe')"
	),
	Array(
		GetMessage("SERVICES_MENU_EVENTLIST"),
		"/edu/services/event_list.php",
		Array(),
		Array(),
		"CBXFeatures::IsFeatureEnabled('EventList')"
	),
	Array(
		GetMessage("SERVICES_MENU_SALARY"),
		"/edu/services/salary/",
		Array(),
		Array(),
		"LANGUAGE_ID == 'ru' && CBXFeatures::IsFeatureEnabled('Salary')"
	),
	Array(
		GetMessage("SERVICES_MENU_BOARD"),
		"/edu/services/board/",
		Array(),
		Array(),
		"CBXFeatures::IsFeatureEnabled('Board')"
	),
	Array(
		GetMessage("SERVICES_MENU_TELEPHONY"),
		"/edu/services/telephony/",
		Array(),
		Array(),
		'CModule::IncludeModule("voximplant") && SITE_TEMPLATE_ID !== "bitrix24" && Bitrix\Voximplant\Security\Helper::isMainMenuEnabled()'
	),
	/*Array(
		GetMessage("SERVICES_MENU_OPENLINES"),
		"/edu/services/openlines/",
		Array(),
		Array(),
		'CModule::IncludeModule("imopenlines") && SITE_TEMPLATE_ID !== "bitrix24" && Bitrix\ImOpenlines\Security\Helper::isMainMenuEnabled()'
	),*/
);
?>