<?php

define('BP_IBLOCK', 598);
define('BP_TEMPLATE_ID', 1013);
define('BP_IBLOCK_PODRAZDELENIYA', 5);
define('BP_SECTION_ORG_ISP_POWER', 1727);
define('BP_SECTION_ORG_ISP_POWER_2', 1710);
define('BP_SECTION_ORG_ISP_POWER_3', 2331);
define('BP_SECTION_ORG_SELF_POWER_1', 2228);
define('BP_SECTION_ORG_SELF_POWER_2', 2237);
define('BP_SECTION_CITTO_DEPARTMENT', 57);
define('BP_SECTION_ROOT', 53);
