<?php

define('BP_TEMPLATE_ID', 928);
define('BP_SECTION_ORG_ISP_POWER', 1727);
define('BP_SECTION_ORG_ISP_POWER_2', 1710);
define('BP_SECTION_ORG_ISP_POWER_3', 2331);
define('BP_SECTION_ORG_SELF_POWER_1', 2228);
define('BP_SECTION_ORG_SELF_POWER_2', 2237);
define('BP_SECTION_CITTO_DEPARTMENT', 57);
define('BP_SECTION_CZN_DEPARTMENT', 2971);
define('BP_SECTION_SIT_CENTR', 3080);
define('BP_SECTION_MIN_INF', 204);
define('BP_SECTION_MIN_TRUD', 461);
define('BP_SECTION_ROOT', 53);
